version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    REPOSITORY_URI: public.ecr.aws/z1f8s7i7/demospace/demo-ecs-app
    IMAGE_TAG: latest
    CONTAINER_NAME: demo-container

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR Public...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

  build:
    commands:
      - echo Build started on `date`
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json